'use client';
import {useCallback,useEffect,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {favoritesKey,parseFavorites,toggleFavorite,modelListSchema,type VehicleModel} from '@selection/core';
export default function Catalog(){
  const t=useTranslations('common');const locale=useLocale();
  const [models,setModels]=useState<VehicleModel[]>([]);const [ids,setIds]=useState<string[]>([]);
  const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [storageError,setStorageError]=useState(false);const [attempt,setAttempt]=useState(0);
  useEffect(()=>{function sync(){try{setIds(parseFavorites(localStorage.getItem(favoritesKey)));}catch{setStorageError(true);}}
    function onStorage(event:StorageEvent){if(event.key===favoritesKey||event.key===null)sync();}sync();window.addEventListener('storage',onStorage);return()=>window.removeEventListener('storage',onStorage);},[]);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/v1/vehicles/models?locale=${locale}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const parsed=modelListSchema.parse(await response.json());setModels(parsed.data);setLoading(false);setError(false);}).catch(()=>{if(!controller.signal.aborted){setError(true);setLoading(false);}});return()=>controller.abort();},[locale,attempt]);
  const save=useCallback((id:string)=>{let current=ids;try{current=parseFavorites(localStorage.getItem(favoritesKey));}catch{setStorageError(true);}const next=toggleFavorite(current,id);setIds(next);try{localStorage.setItem(favoritesKey,JSON.stringify({version:1,modelIds:next}));setStorageError(false);}catch{setStorageError(true);}},[ids]);
  return <div className="catalog-grid"><section className="glass panel" aria-labelledby="catalog-title"><div className="section-heading"><span className="section-number" aria-hidden="true">01</span><h2 id="catalog-title">{t('catalog')}</h2></div>{loading?<p role="status">{t('loading')}</p>:error?<div role="alert"><p>{t('error')}</p><button onClick={()=>{setLoading(true);setAttempt(value=>value+1);}}>{t('retry')}</button></div>:models.length?<ul>{models.map(model=><li key={model.id}><span>{model.label}</span><button onClick={()=>save(model.id)} aria-pressed={ids.includes(model.id)}>{t(ids.includes(model.id)?'removeFavorite':'addFavorite')}</button></li>)}</ul>:<div className="empty-state"><svg className="vehicle-icon" viewBox="0 0 80 48" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M12 32V22l7-4 7-12h27l9 12 7 4v10M20 32h38M21 18h38M31 6l-4 12m18-12 4 12"/><circle cx="19" cy="33" r="6"/><circle cx="61" cy="33" r="6"/></svg><h3>{t('emptyCatalog')}</h3><p>{t('emptyDescription')}</p></div>}</section><section className="glass panel" aria-labelledby="favorites-title"><div className="section-heading"><span className="section-number" aria-hidden="true">02</span><h2 id="favorites-title">{t('favorites')}</h2><span className="count">{new Intl.NumberFormat(locale).format(ids.length)}</span></div>{storageError&&<p role="alert">{t('storageError')}</p>}{ids.length?<ul>{ids.map(id=><li key={id}><span>{models.find(model=>model.id===id)?.label||t('unavailableModel')}</span><button onClick={()=>save(id)} aria-label={t('removeFavorite')}>{t('remove')}</button></li>)}</ul>:<div className="empty-state"><span className="favorite-icon" aria-hidden="true">☆</span><h3>{t('emptyFavorites')}</h3><p>{t('favoriteHint')}</p></div>}</section></div>;
}
