'use client';
import {useEffect,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {useSearchParams} from 'next/navigation';
import {favoritesKey,parseFavorites,toggleFavorite,modelListSchema,selectionSchema,emptySelection,categoriesSchema,partsResultSchema,type Selection,type VehicleModel,type PartResults} from '@selection/core';
import SearchSelect from './search-select';
import PartsList from './parts-list';
type Categories=ReturnType<typeof categoriesSchema.parse>['data'];
const vehicleFields=['kind','makeId','modelId','fuel','body','transmission','variantId'] as const;
function useResource<T>(url:string|null,parse:(value:unknown)=>T){
 const [state,setState]=useState<{url:string|null;data:T|null;loading:boolean;error:boolean}>({url:null,data:null,loading:false,error:false});const [attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!url)return;const controller=new AbortController();fetch(url,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=parse(await response.json());setState({url,data,loading:false,error:false});}).catch(()=>{if(!controller.signal.aborted)setState({url,data:null,loading:false,error:true});});return()=>controller.abort();},[url,parse,attempt]);
 return {data:url&&state.url===url?state.data:null,loading:!!url&&state.url!==url,error:!!url&&state.url===url&&state.error,retry:()=>{setState({url:null,data:null,loading:false,error:false});setAttempt(v=>v+1);}};
}
const parseSelection=(v:unknown)=>selectionSchema.parse(v),parseModels=(v:unknown)=>modelListSchema.parse(v),parseCategories=(v:unknown)=>categoriesSchema.parse(v),parseParts=(v:unknown)=>partsResultSchema.parse(v);
export default function Catalog(){
 const t=useTranslations('common');const locale=useLocale();const searchParams=useSearchParams();const queryString=searchParams.toString();const kind=searchParams.get('kind')==='motorcycle'?'motorcycle':'car';
 const makeId=searchParams.get('makeId')||'',modelId=searchParams.get('modelId')||'',fuel=searchParams.get('fuel')||'',body=searchParams.get('body')||'',transmission=searchParams.get('transmission')||'',variantId=searchParams.get('variantId')||'',categoryId=searchParams.get('categoryId')||'';
 const [ids,setIds]=useState<string[]>([]),[storageError,setStorageError]=useState(false);
 const selectionParams=new URLSearchParams({locale,kind});for(const [key,value] of Object.entries({makeId,modelId,fuel,body,transmission}))if(value)selectionParams.set(key,value);
 const selectionResource=useResource<Selection>('/api/v1/vehicles/selection?'+selectionParams,parseSelection);const selection=selectionResource.data||emptySelection;
 const model=selection.models.find(m=>m.id===modelId),variant=selection.variants.find(v=>v.id===variantId);
 const categoriesResource=useResource(variant?`/api/v1/parts/categories?locale=${locale}&variantId=${encodeURIComponent(variant.id)}`:null,parseCategories);const categories:Categories=categoriesResource.data?.data||[];const category=categories.find(c=>c.id===categoryId);
 const page=Math.max(1,Math.min(10000,Number(searchParams.get('page'))||1));
 const partsResource=useResource<PartResults>(variant&&category?.hasParts?`/api/v1/parts/by-vehicle?${new URLSearchParams({locale,variantId:variant.id,categoryId:category.id,page:String(page)})}`:null,parseParts);
 const favorites=useResource(ids.length?`/api/v1/vehicles/models?${new URLSearchParams({locale,ids:ids.join(',')})}`:null,parseModels);
 useEffect(()=>{function sync(){try{setIds(parseFavorites(localStorage.getItem(favoritesKey)));}catch{setStorageError(true);}}function onStorage(event:StorageEvent){if(event.key===favoritesKey||event.key===null)sync();}sync();window.addEventListener('storage',onStorage);return()=>window.removeEventListener('storage',onStorage);},[]);
 function update(values:Record<string,string>,reset:string[]=[]){const query=new URLSearchParams(queryString);for(const key of reset)query.delete(key);for(const [key,value] of Object.entries(values)){if(value)query.set(key,value);else query.delete(key);}window.history.replaceState(null,'',`${window.location.pathname}${query.size?'?'+query:''}${window.location.hash}`);}
 function change(field:typeof vehicleFields[number],value:string){update({[field]:value},[...vehicleFields.slice(vehicleFields.indexOf(field)+1),'categoryId','page']);}
 function save(id:string){let current=ids;try{current=parseFavorites(localStorage.getItem(favoritesKey));}catch{setStorageError(true);}const next=toggleFavorite(current,id);setIds(next);try{localStorage.setItem(favoritesKey,JSON.stringify({version:1,modelIds:next}));setStorageError(false);}catch{setStorageError(true);}}
 function restore(m:VehicleModel){update({kind:m.kind||'car',makeId:m.makeId,modelId:m.id},['fuel','body','transmission','variantId','categoryId','page']);}
 const modelName=(m:VehicleModel)=>`${m.makeLabel||''} ${m.label||t('unnamedModel',{id:m.sourceId})}`.trim();
 function valueLabel(value:string){return t.has('values.'+value)?t('values.'+value):value;}
 const all=t('any');const options=(values:string[])=>[{id:'',label:all},...values.map(v=>({id:v,label:valueLabel(v)}))];
 function date(value:string|null){return value?new Intl.DateTimeFormat(locale,{month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(value)):t('unknownDate');}
 function variantLabel(v:Selection['variants'][number]){return t('variantLabel',{name:v.label,power:v.powerKw===null?t('unknownPower'):new Intl.NumberFormat(locale).format(v.powerKw),from:date(v.productionFrom),to:date(v.productionTo),engine:v.engineCode||t('unknownEngine')});}
 const path:Categories=[];let current=category;const visited=new Set<string>();while(current&&!visited.has(current.id)){visited.add(current.id);path.unshift(current);current=categories.find(c=>c.id===current?.parentId);}
 const levels=[{parentId:null as string|null,value:path[0]?.id||''},...path.map((c,i)=>({parentId:c.id,value:path[i+1]?.id||''}))].filter(l=>categories.some(c=>c.parentId===l.parentId));
 const fieldProps={placeholder:t('choose'),refine:t('refine')};
 return <div className="catalog-grid"><section className="glass panel" aria-labelledby="catalog-title"><div className="section-heading"><span className="section-number" aria-hidden="true">01</span><h2 id="catalog-title">{t('catalog')}</h2></div>
  <div className="part-search"><label htmlFor="part-search">{t('partSearch')}</label><input id="part-search" placeholder={t('searchPlaceholder')} disabled aria-describedby="search-note"/><p id="search-note" className="field-hint">{t('searchUnavailable')}</p></div>
  <h3 className="block-title">{t('vehicleSelection')}</h3><div className="kind-switch" role="group" aria-label={t('vehicleKind')}><button aria-pressed={kind==='car'} onClick={()=>change('kind','car')}>{t('car')}</button><button aria-pressed={kind==='motorcycle'} onClick={()=>change('kind','motorcycle')}>{t('motorcycle')}</button></div>
  {selectionResource.loading&&<p role="status">{t('loading')}</p>}{selectionResource.error&&<div role="alert"><p>{t('error')}</p><button onClick={selectionResource.retry}>{t('retry')}</button></div>}
  <div className="filter-grid"><SearchSelect {...fieldProps} label={t('make')} value={makeId} options={selection.makes} disabled={!selection.makes.length} onChange={v=>change('makeId',v)}/><SearchSelect {...fieldProps} label={t('model')} value={modelId} options={selection.models.map(m=>({id:m.id,label:m.label||t('unnamedModel',{id:m.sourceId})}))} disabled={!selection.models.length} onChange={v=>change('modelId',v)}/><SearchSelect {...fieldProps} label={t('fuel')} value={fuel} options={options(selection.fuels)} disabled={!model} onChange={v=>change('fuel',v)}/><SearchSelect {...fieldProps} label={t('body')} value={body} options={options(selection.bodies)} disabled={!model} onChange={v=>change('body',v)}/><SearchSelect {...fieldProps} label={t('transmission')} value={transmission} options={options(selection.transmissions)} disabled={!model} onChange={v=>change('transmission',v)}/><SearchSelect {...fieldProps} label={t('variant')} value={variantId} options={selection.variants.map(v=>({id:v.id,label:variantLabel(v)}))} disabled={!selection.variants.length} onChange={v=>change('variantId',v)}/></div>
  {model&&selection.transmissions.length===1&&selection.transmissions[0]==='unknown'&&<p className="field-hint">{t('missingTransmission')}</p>}
  {selection.totalVariants>selection.variants.length&&<p className="field-hint">{t('narrowVariants')}</p>}
  {!selectionResource.loading&&!selectionResource.error&&!selection.makes.length&&<p className="field-hint">{t('emptyDescription')}</p>}
  <div className="parts-filter"><h3 className="block-title">{t('partsSelection')}</h3>{!variant?<p className="field-hint">{t('chooseVariant')}</p>:categoriesResource.loading?<p role="status">{t('loadingGroups')}</p>:categoriesResource.error?<div role="alert"><p>{t('error')}</p><button onClick={categoriesResource.retry}>{t('retry')}</button></div>:!categories.length?<p className="field-hint">{t('noImportedParts')}</p>:levels.map((level,i)=><SearchSelect key={level.parentId||'root'} {...fieldProps} label={t(i===0?'partType':i===1?'partGroup':'partSubgroup')} value={level.value} options={categories.filter(c=>c.parentId===level.parentId).map(c=>({id:c.id,label:c.label})).sort((a,b)=>a.label.localeCompare(b.label,locale))} onChange={v=>update({categoryId:v},['page'])}/>)}</div>
  {ids.length>0&&<div className="saved-models"><h3 className="block-title">{t('favorites')}</h3><ul>{ids.map(id=>{const m=favorites.data?.data.find(v=>v.id===id);return <li key={id}>{m?<button className="favorite-link" onClick={()=>restore(m)}>{modelName(m)}</button>:<span>{favorites.loading?t('loading'):t('unavailableModel')}</span>}<button className="icon-button" aria-label={t('removeFavorite')} onClick={()=>save(id)}>×</button></li>;})}</ul></div>}
 </section><section className="glass panel results-panel" aria-labelledby="selected-title"><div className="section-heading"><span className="section-number" aria-hidden="true">02</span><h2 id="selected-title">{t('selectedVehicle')}</h2></div>
  {model?<div className="selected-vehicle"><div className="vehicle-name"><h3>{modelName(model)}</h3><button className="star-button" aria-label={t(ids.includes(model.id)?'removeFavorite':'addFavorite')} aria-pressed={ids.includes(model.id)} onClick={()=>save(model.id)}>{ids.includes(model.id)?'★':'☆'}</button></div>{variant?<p>{variantLabel(variant)}</p>:<p className="field-hint">{t('chooseVariant')}</p>}</div>:<div className="empty-state"><svg className="vehicle-icon" viewBox="0 0 80 48" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M12 32V22l7-4 7-12h27l9 12 7 4v10M20 32h38M21 18h38M31 6l-4 12m18-12 4 12"/><circle cx="19" cy="33" r="6"/><circle cx="61" cy="33" r="6"/></svg><h3>{t('chooseVehicle')}</h3><p>{t('selectionHint')}</p></div>}
  {storageError&&<p role="alert">{t('storageError')}</p>}
  {model&&<div className="part-results"><h3 className="block-title">{category?.label||t('results')}</h3>{!variant||!category?.hasParts?<p className="field-hint">{t('choosePartGroup')}</p>:partsResource.loading?<p role="status">{t('loadingParts')}</p>:partsResource.error?<div role="alert"><p>{t('error')}</p><button onClick={partsResource.retry}>{t('retry')}</button></div>:partsResource.data&&<><p className="field-hint">{t('resultCount',{count:partsResource.data.total})}</p><PartsList data={partsResource.data.data}/>{partsResource.data.total>partsResource.data.limit&&<nav className="pagination" aria-label={t('pagination')}><button disabled={page<=1} onClick={()=>update({page:String(page-1)})}>{t('previous')}</button><span>{t('pageOf',{page,total:Math.ceil(partsResource.data.total/partsResource.data.limit)})}</span><button disabled={page*partsResource.data.limit>=partsResource.data.total} onClick={()=>update({page:String(page+1)})}>{t('next')}</button></nav>}</>}</div>}
 </section></div>;
}
